"""M3 persistence: identity, workspace, ingestion, mapping, change requests, pipeline results,
issues, audit and jobs.

Generated with autogenerate, then edited: plain SQL column types (no application type
decorators), cycle-closing foreign keys added after all tables, append-only and
segregation-of-duties triggers.

Revision ID: 0002_persistence
Revises: 0001_baseline
Create Date: 2026-09-17 13:48:06.961652+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002_persistence"
down_revision: str | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

APPEND_ONLY_TABLES = ("source_rows", "quarantined_rows", "audit_events")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("migration_id", sa.UUID(), nullable=True),
        sa.Column("migration_seq", sa.BigInteger(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_type", sa.Text(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("change_request_id", sa.UUID(), nullable=True),
        sa.Column("evidence_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column("prev_hash", sa.Text(), nullable=False),
        sa.Column("hash", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "actor_type IN ('user', 'system', 'ai')", name=op.f("ck_audit_events_actor_type")
        ),
        sa.PrimaryKeyConstraint("seq", name=op.f("pk_audit_events")),
        sa.UniqueConstraint("id", name=op.f("uq_audit_events_id")),
        sa.UniqueConstraint(
            "migration_id",
            "migration_seq",
            name=op.f("uq_audit_events_migration_id_migration_seq"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        "ix_audit_events_entity",
        "audit_events",
        ["migration_id", "entity_type", "entity_id"],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_occurred", "audit_events", ["migration_id", "occurred_at"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dedupe_key", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("run_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_by", sa.Text(), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('parse_import', 'profile_import', 'run_pipeline')", name=op.f("ck_jobs_kind")
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed', 'dead')",
            name=op.f("ck_jobs_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_jobs_dedupe_key")),
    )
    op.create_index(
        "ix_jobs_queued",
        "jobs",
        ["run_after"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('implementation_specialist', 'implementation_lead', 'customer_controller', 'admin', 'viewer')",
            name=op.f("ck_users_role"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(
        "uq_users_email_lower", "users", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "companies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("legal_name", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), nullable=False),
        sa.Column("functional_currency", sa.CHAR(length=3), nullable=False),
        sa.Column("fiscal_year_start_month", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "fiscal_year_start_month BETWEEN 1 AND 12",
            name=op.f("ck_companies_fiscal_year_start_month"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_companies_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    op.create_table(
        "stored_files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("media_type", sa.Text(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column(
            "first_uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("first_uploaded_by", sa.UUID(), nullable=True),
        sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_stored_files_sha256_hex")),
        sa.ForeignKeyConstraint(
            ["first_uploaded_by"],
            ["users.id"],
            name=op.f("fk_stored_files_first_uploaded_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stored_files")),
        sa.UniqueConstraint("sha256", name=op.f("uq_stored_files_sha256")),
    )
    op.create_table(
        "migrations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("functional_currency", sa.CHAR(length=3), nullable=False),
        sa.Column("fiscal_year_start_month", sa.SmallInteger(), nullable=False),
        sa.Column("opening_balance_date", sa.Date(), nullable=False),
        sa.Column("history_start_date", sa.Date(), nullable=False),
        sa.Column("cutover_date", sa.Date(), nullable=False),
        sa.Column("go_live_date", sa.Date(), nullable=False),
        sa.Column("bank_clearing_window_days", sa.Integer(), nullable=False),
        sa.Column("issue_key_prefix", sa.Text(), nullable=False),
        sa.Column("next_issue_number", sa.Integer(), nullable=False),
        sa.Column("next_change_request_number", sa.Integer(), nullable=False),
        sa.Column("lead_user_id", sa.UUID(), nullable=True),
        sa.Column("ai_enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "issue_key_prefix ~ '^[A-Z]{2,6}$'", name=op.f("ck_migrations_issue_key_prefix")
        ),
        sa.CheckConstraint(
            "status IN ('planning', 'in_progress', 'signed_off', 'launched', 'archived')",
            name=op.f("ck_migrations_status"),
        ),
        sa.CheckConstraint(
            "bank_clearing_window_days BETWEEN 0 AND 90", name=op.f("ck_migrations_clearing_window")
        ),
        sa.CheckConstraint(
            "opening_balance_date < history_start_date AND history_start_date <= cutover_date AND cutover_date < go_live_date",
            name=op.f("ck_migrations_conversion_plan_order"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_migrations_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_migrations_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["lead_user_id"], ["users.id"], name=op.f("fk_migrations_lead_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_migrations")),
    )
    op.create_table(
        "change_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("migration_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("justification", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("impact", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("evidence_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("origin", sa.Text(), nullable=False),
        sa.Column("requested_by", sa.UUID(), nullable=False),
        sa.Column("base_fingerprint", sa.Text(), nullable=True),
        sa.Column("base_entity_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("required_approvals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('column_mapping_set', 'account_mapping_set', 'record_override', 'entity_decision', 'disposition', 'policy_change', 'gate_waiver', 'readiness_signoff')",
            name=op.f("ck_change_requests_kind"),
        ),
        sa.CheckConstraint(
            "origin IN ('operator', 'ai_finding')", name=op.f("ck_change_requests_origin")
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'submitted', 'approved', 'rejected', 'withdrawn', 'applied', 'stale', 'failed_to_apply')",
            name=op.f("ck_change_requests_status"),
        ),
        sa.ForeignKeyConstraint(
            ["migration_id"],
            ["migrations.id"],
            name=op.f("fk_change_requests_migration_id_migrations"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["users.id"], name=op.f("fk_change_requests_requested_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_requests")),
        sa.UniqueConstraint(
            "migration_id", "key", name=op.f("uq_change_requests_migration_id_key")
        ),
    )
    op.create_table(
        "policy_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("migration_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("change_request_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_policy_versions_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["migration_id"],
            ["migrations.id"],
            name=op.f("fk_policy_versions_migration_id_migrations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_versions")),
        sa.UniqueConstraint(
            "migration_id", "version", name=op.f("uq_policy_versions_migration_id_version")
        ),
    )
    op.create_table(
        "source_systems",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("migration_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('legacy_erp', 'spreadsheet', 'bank', 'billing', 'crm', 'other')",
            name=op.f("ck_source_systems_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_source_systems_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["migration_id"],
            ["migrations.id"],
            name=op.f("fk_source_systems_migration_id_migrations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_systems")),
        sa.UniqueConstraint(
            "migration_id", "name", name=op.f("uq_source_systems_migration_id_name")
        ),
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("change_request_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_user_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_role_at_decision", sa.Text(), nullable=False),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("satisfies_requirement_index", sa.Integer(), nullable=True),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("decision IN ('approve', 'reject')", name=op.f("ck_approvals_decision")),
        sa.ForeignKeyConstraint(
            ["change_request_id"],
            ["change_requests.id"],
            name=op.f("fk_approvals_change_request_id_change_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"], ["users.id"], name=op.f("fk_approvals_reviewer_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
        sa.UniqueConstraint(
            "change_request_id",
            "reviewer_user_id",
            name=op.f("uq_approvals_change_request_id_reviewer_user_id"),
        ),
    )
    op.create_table(
        "datasets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("migration_id", sa.UUID(), nullable=False),
        sa.Column("source_system_id", sa.UUID(), nullable=False),
        sa.Column("dataset_type", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=True),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active_import_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(dataset_type IN ('ar_aging', 'ap_aging')) = (as_of_date IS NOT NULL)",
            name=op.f("ck_datasets_as_of_date_for_agings"),
        ),
        sa.CheckConstraint(
            "dataset_type IN ('legacy_coa', 'target_coa', 'account_mapping', 'gl_detail', 'trial_balance', 'customers', 'vendors', 'invoices', 'bills', 'payments', 'ar_aging', 'ap_aging', 'bank_transactions', 'fx_rates')",
            name=op.f("ck_datasets_dataset_type"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_datasets_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["migration_id"], ["migrations.id"], name=op.f("fk_datasets_migration_id_migrations")
        ),
        sa.ForeignKeyConstraint(
            ["source_system_id"],
            ["source_systems.id"],
            name=op.f("fk_datasets_source_system_id_source_systems"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_datasets")),
        sa.UniqueConstraint(
            "migration_id",
            "source_system_id",
            "dataset_type",
            "as_of_date",
            name=op.f("uq_datasets_migration_id_source_system_id_dataset_type_as_of_date"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("migration_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sa.Text(), nullable=False),
        sa.Column(
            "fingerprint_components", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("result_fingerprint", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("trigger", sa.Text(), nullable=False),
        sa.Column("triggered_by_user_id", sa.UUID(), nullable=True),
        sa.Column("change_request_id", sa.UUID(), nullable=True),
        sa.Column("stage_timings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed')",
            name=op.f("ck_pipeline_runs_status"),
        ),
        sa.CheckConstraint(
            "trigger IN ('manual', 'change_request_applied', 'import_activated')",
            name=op.f("ck_pipeline_runs_trigger"),
        ),
        sa.ForeignKeyConstraint(
            ["change_request_id"],
            ["change_requests.id"],
            name=op.f("fk_pipeline_runs_change_request_id_change_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["migration_id"],
            ["migrations.id"],
            name=op.f("fk_pipeline_runs_migration_id_migrations"),
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by_user_id"],
            ["users.id"],
            name=op.f("fk_pipeline_runs_triggered_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_runs")),
        sa.UniqueConstraint(
            "migration_id", "sequence", name=op.f("uq_pipeline_runs_migration_id_sequence")
        ),
    )
    op.create_index(
        "uq_pipeline_runs_active_fingerprint",
        "pipeline_runs",
        ["migration_id", "fingerprint"],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_index(
        "uq_pipeline_runs_succeeded_fingerprint",
        "pipeline_runs",
        ["migration_id", "fingerprint"],
        unique=True,
        postgresql_where=sa.text("status = 'succeeded'"),
    )
    op.create_table(
        "entity_candidates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("party_type", sa.Text(), nullable=False),
        sa.Column("left_code", sa.Text(), nullable=False),
        sa.Column("right_code", sa.Text(), nullable=False),
        sa.Column("score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("strong", sa.Boolean(), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "status IN ('open', 'decided_same', 'decided_distinct')",
            name=op.f("ck_entity_candidates_status"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["pipeline_runs.id"], name=op.f("fk_entity_candidates_run_id_pipeline_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_candidates")),
        sa.UniqueConstraint(
            "run_id",
            "party_type",
            "left_code",
            "right_code",
            name=op.f("uq_entity_candidates_run_id_party_type_left_code_right_code"),
        ),
    )
    op.create_table(
        "imports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("stored_file_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("encoding", sa.Text(), nullable=True),
        sa.Column("delimiter", sa.Text(), nullable=True),
        sa.Column("header", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("quarantined_count", sa.Integer(), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'parsing', 'parsed', 'failed', 'superseded')",
            name=op.f("ck_imports_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_imports_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["datasets.id"], name=op.f("fk_imports_dataset_id_datasets")
        ),
        sa.ForeignKeyConstraint(
            ["stored_file_id"],
            ["stored_files.id"],
            name=op.f("fk_imports_stored_file_id_stored_files"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_imports")),
        sa.UniqueConstraint("dataset_id", "sequence", name=op.f("uq_imports_dataset_id_sequence")),
        sa.UniqueConstraint(
            "dataset_id", "stored_file_id", name=op.f("uq_imports_dataset_id_stored_file_id")
        ),
    )
    op.create_table(
        "issues",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("migration_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("fingerprint", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("rule_or_recon_id", sa.Text(), nullable=True),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("nature", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("subjects", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("amount_at_risk", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("first_seen_run_id", sa.UUID(), nullable=True),
        sa.Column("last_seen_run_id", sa.UUID(), nullable=True),
        sa.Column("verified_absent_run_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "source IN ('rule', 'reconciliation', 'normalization', 'manual')",
            name=op.f("ck_issues_source"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'in_progress', 'awaiting_verification', 'resolved', 'dispositioned', 'closed')",
            name=op.f("ck_issues_status"),
        ),
        sa.ForeignKeyConstraint(
            ["first_seen_run_id"],
            ["pipeline_runs.id"],
            name=op.f("fk_issues_first_seen_run_id_pipeline_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["last_seen_run_id"],
            ["pipeline_runs.id"],
            name=op.f("fk_issues_last_seen_run_id_pipeline_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["migration_id"], ["migrations.id"], name=op.f("fk_issues_migration_id_migrations")
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"], ["users.id"], name=op.f("fk_issues_owner_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["verified_absent_run_id"],
            ["pipeline_runs.id"],
            name=op.f("fk_issues_verified_absent_run_id_pipeline_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issues")),
        sa.UniqueConstraint(
            "migration_id", "fingerprint", name=op.f("uq_issues_migration_id_fingerprint")
        ),
        sa.UniqueConstraint("migration_id", "key", name=op.f("uq_issues_migration_id_key")),
    )
    op.create_index(
        "ix_issues_status_severity", "issues", ["migration_id", "status", "severity"], unique=False
    )
    op.create_table(
        "readiness_evaluations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("overall", sa.Text(), nullable=False),
        sa.Column(
            "unresolved_exposure",
            sa.Numeric(precision=20, scale=4),
            nullable=False,
        ),
        sa.Column("facts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "evaluated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["pipeline_runs.id"],
            name=op.f("fk_readiness_evaluations_run_id_pipeline_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_readiness_evaluations")),
        sa.UniqueConstraint("run_id", name=op.f("uq_readiness_evaluations_run_id")),
    )
    op.create_table(
        "reconciliation_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("recon_id", sa.Text(), nullable=False),
        sa.Column("recon_version", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("applicable", sa.Boolean(), nullable=False),
        sa.Column("left_label", sa.Text(), nullable=False),
        sa.Column("right_label", sa.Text(), nullable=False),
        sa.Column("tolerance", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("line_count", sa.Integer(), nullable=False),
        sa.Column("discrepancy_count", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["pipeline_runs.id"],
            name=op.f("fk_reconciliation_results_run_id_pipeline_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconciliation_results")),
        sa.UniqueConstraint(
            "run_id", "recon_id", name=op.f("uq_reconciliation_results_run_id_recon_id")
        ),
    )
    op.create_table(
        "rule_exceptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.Text(), nullable=False),
        sa.Column("rule_version", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("nature", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("subjects", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("discriminator", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("expected", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("observed", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("amount_at_risk", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("lineage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["pipeline_runs.id"], name=op.f("fk_rule_exceptions_run_id_pipeline_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_exceptions")),
        sa.UniqueConstraint(
            "run_id", "fingerprint", name=op.f("uq_rule_exceptions_run_id_fingerprint")
        ),
    )
    op.create_index(
        "ix_rule_exceptions_rule", "rule_exceptions", ["run_id", "rule_id"], unique=False
    )
    op.create_table(
        "rule_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.Text(), nullable=False),
        sa.Column("rule_version", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("exception_count", sa.Integer(), nullable=False),
        sa.Column("missing_datasets", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.CheckConstraint(
            "status IN ('passed', 'failed', 'not_applicable')", name=op.f("ck_rule_runs_status")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["pipeline_runs.id"], name=op.f("fk_rule_runs_run_id_pipeline_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_runs")),
        sa.UniqueConstraint("run_id", "rule_id", name=op.f("uq_rule_runs_run_id_rule_id")),
    )
    op.create_table(
        "column_mapping_sets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("based_on_import_id", sa.UUID(), nullable=True),
        sa.Column("change_request_id", sa.UUID(), nullable=True),
        sa.Column("exclude_rows_where_blank", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'pending_approval', 'approved', 'superseded', 'rejected')",
            name=op.f("ck_column_mapping_sets_status"),
        ),
        sa.ForeignKeyConstraint(
            ["based_on_import_id"],
            ["imports.id"],
            name=op.f("fk_column_mapping_sets_based_on_import_id_imports"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_column_mapping_sets_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["datasets.id"], name=op.f("fk_column_mapping_sets_dataset_id_datasets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_column_mapping_sets")),
        sa.UniqueConstraint(
            "dataset_id", "version", name=op.f("uq_column_mapping_sets_dataset_id_version")
        ),
    )
    op.create_index(
        "uq_column_mapping_sets_one_approved",
        "column_mapping_sets",
        ["dataset_id"],
        unique=True,
        postgresql_where=sa.text("status = 'approved'"),
    )
    op.create_table(
        "dataset_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("import_id", sa.UUID(), nullable=False),
        sa.Column("profiler_version", sa.Integer(), nullable=False),
        sa.Column("profile", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["import_id"], ["imports.id"], name=op.f("fk_dataset_profiles_import_id_imports")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_profiles")),
        sa.UniqueConstraint("import_id", name=op.f("uq_dataset_profiles_import_id")),
    )
    op.create_table(
        "gate_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("evaluation_id", sa.UUID(), nullable=False),
        sa.Column("gate_id", sa.Text(), nullable=False),
        sa.Column("gate_version", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("blocking", sa.Boolean(), nullable=False),
        sa.Column("observed", sa.Text(), nullable=False),
        sa.Column("threshold", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("evidence", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("waiver_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["readiness_evaluations.id"],
            name=op.f("fk_gate_results_evaluation_id_readiness_evaluations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gate_results")),
        sa.UniqueConstraint(
            "evaluation_id", "gate_id", name=op.f("uq_gate_results_evaluation_id_gate_id")
        ),
    )
    op.create_table(
        "issue_occurrences",
        sa.Column("issue_id", sa.UUID(), nullable=False),
        sa.Column("rule_exception_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["issue_id"], ["issues.id"], name=op.f("fk_issue_occurrences_issue_id_issues")
        ),
        sa.ForeignKeyConstraint(
            ["rule_exception_id"],
            ["rule_exceptions.id"],
            name=op.f("fk_issue_occurrences_rule_exception_id_rule_exceptions"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["pipeline_runs.id"], name=op.f("fk_issue_occurrences_run_id_pipeline_runs")
        ),
        sa.PrimaryKeyConstraint("issue_id", "rule_exception_id", name=op.f("pk_issue_occurrences")),
    )
    op.create_table(
        "quarantined_rows",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("import_id", sa.UUID(), nullable=False),
        sa.Column("quarantine_key", sa.Text(), nullable=False),
        sa.Column("line_start", sa.Integer(), nullable=False),
        sa.Column("line_end", sa.Integer(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("field_counts", postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.CheckConstraint(
            "reason IN ('field_count_mismatch', 'unterminated_quote', 'field_too_long')",
            name=op.f("ck_quarantined_rows_reason"),
        ),
        sa.ForeignKeyConstraint(
            ["import_id"], ["imports.id"], name=op.f("fk_quarantined_rows_import_id_imports")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quarantined_rows")),
        sa.UniqueConstraint(
            "import_id", "line_start", name=op.f("uq_quarantined_rows_import_id_line_start")
        ),
    )
    op.create_table(
        "reconciliation_lines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("result_id", sa.UUID(), nullable=False),
        sa.Column("grain_key", sa.Text(), nullable=False),
        sa.Column("grain", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("left_amount", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("right_amount", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("difference", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column(
            "explained_amount",
            sa.Numeric(precision=20, scale=4),
            nullable=False,
        ),
        sa.Column(
            "unexplained_amount",
            sa.Numeric(precision=20, scale=4),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "status IN ('tied', 'within_tolerance', 'explained', 'discrepancy')",
            name=op.f("ck_reconciliation_lines_status"),
        ),
        sa.ForeignKeyConstraint(
            ["result_id"],
            ["reconciliation_results.id"],
            name=op.f("fk_reconciliation_lines_result_id_reconciliation_results"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconciliation_lines")),
        sa.UniqueConstraint(
            "result_id", "grain_key", name=op.f("uq_reconciliation_lines_result_id_grain_key")
        ),
    )
    op.create_index(
        "ix_reconciliation_lines_status",
        "reconciliation_lines",
        ["result_id", "status"],
        unique=False,
    )
    op.create_table(
        "source_rows",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("import_id", sa.UUID(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("line_start", sa.Integer(), nullable=False),
        sa.Column("line_end", sa.Integer(), nullable=False),
        sa.Column("values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("row_hash", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["import_id"], ["imports.id"], name=op.f("fk_source_rows_import_id_imports")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_rows")),
        sa.UniqueConstraint(
            "import_id", "row_number", name=op.f("uq_source_rows_import_id_row_number")
        ),
    )
    op.create_table(
        "staged_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("record_type", sa.Text(), nullable=False),
        sa.Column("natural_key", sa.Text(), nullable=False),
        sa.Column("account_code", sa.Text(), nullable=True),
        sa.Column("party_code", sa.Text(), nullable=True),
        sa.Column("document_number", sa.Text(), nullable=True),
        sa.Column("entry_number", sa.Text(), nullable=True),
        sa.Column("record_date", sa.Date(), nullable=True),
        sa.Column("posting_period", sa.Text(), nullable=True),
        sa.Column(
            "functional_amount",
            sa.Numeric(precision=20, scale=4),
            nullable=True,
        ),
        sa.Column("source_import_id", sa.UUID(), nullable=True),
        sa.Column("source_row_number", sa.Integer(), nullable=True),
        sa.Column("line_start", sa.Integer(), nullable=True),
        sa.Column("line_end", sa.Integer(), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["pipeline_runs.id"], name=op.f("fk_staged_records_run_id_pipeline_runs")
        ),
        sa.ForeignKeyConstraint(
            ["source_import_id"],
            ["imports.id"],
            name=op.f("fk_staged_records_source_import_id_imports"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staged_records")),
        sa.UniqueConstraint(
            "run_id", "natural_key", name=op.f("uq_staged_records_run_id_natural_key")
        ),
    )
    op.create_index(
        "ix_staged_records_document", "staged_records", ["run_id", "document_number"], unique=False
    )
    op.create_index(
        "ix_staged_records_party", "staged_records", ["run_id", "party_code"], unique=False
    )
    op.create_index(
        "ix_staged_records_type_account",
        "staged_records",
        ["run_id", "record_type", "account_code"],
        unique=False,
    )
    op.create_table(
        "column_mappings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mapping_set_id", sa.UUID(), nullable=False),
        sa.Column("target_field", sa.Text(), nullable=False),
        sa.Column("transform", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("basis", sa.Text(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "basis IN ('exact', 'synonym', 'operator', 'ai_suggested')",
            name=op.f("ck_column_mappings_basis"),
        ),
        sa.ForeignKeyConstraint(
            ["mapping_set_id"],
            ["column_mapping_sets.id"],
            name=op.f("fk_column_mappings_mapping_set_id_column_mapping_sets"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_column_mappings")),
        sa.UniqueConstraint(
            "mapping_set_id",
            "target_field",
            name=op.f("uq_column_mappings_mapping_set_id_target_field"),
        ),
    )
    op.create_table(
        "reconciling_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("line_id", sa.UUID(), nullable=False),
        sa.Column("classification", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("record_keys", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["reconciliation_lines.id"],
            name=op.f("fk_reconciling_items_line_id_reconciliation_lines"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconciling_items")),
    )
    # ### end Alembic commands ###

    # Foreign keys that close dependency cycles are added after every table exists.
    op.create_foreign_key(
        "fk_policy_versions_cr", "policy_versions", "change_requests", ["change_request_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_datasets_active_import_id_imports", "datasets", "imports", ["active_import_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_column_mapping_sets_cr",
        "column_mapping_sets",
        "change_requests",
        ["change_request_id"],
        ["id"],
    )

    # FC-08, GV-06: append-only tables reject UPDATE, DELETE and TRUNCATE.
    op.execute(
        """
        CREATE FUNCTION relay_reject_modification() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'relay: % on % is not allowed (append-only table)', TG_OP, TG_TABLE_NAME
                USING ERRCODE = 'insufficient_privilege';
        END;
        $$
        """
    )
    for table in APPEND_ONLY_TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION relay_reject_modification()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION relay_reject_modification()"
        )

    # GV-02: a reviewer can never approve or reject their own change request.
    op.execute(
        """
        CREATE FUNCTION relay_approval_segregation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF NEW.reviewer_user_id = (
                SELECT requested_by FROM change_requests WHERE id = NEW.change_request_id
            ) THEN
                RAISE EXCEPTION 'relay: requester cannot review their own change request'
                    USING ERRCODE = 'check_violation';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        "CREATE TRIGGER approvals_segregation BEFORE INSERT OR UPDATE ON approvals "
        "FOR EACH ROW EXECUTE FUNCTION relay_approval_segregation()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER approvals_segregation ON approvals")
    op.execute("DROP FUNCTION relay_approval_segregation()")
    for table in APPEND_ONLY_TABLES:
        op.execute(f"DROP TRIGGER {table}_no_truncate ON {table}")
        op.execute(f"DROP TRIGGER {table}_append_only ON {table}")
    op.execute("DROP FUNCTION relay_reject_modification()")
    op.drop_constraint("fk_policy_versions_cr", "policy_versions", type_="foreignkey")
    op.drop_constraint("fk_datasets_active_import_id_imports", "datasets", type_="foreignkey")
    op.drop_constraint("fk_column_mapping_sets_cr", "column_mapping_sets", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reconciling_items")
    op.drop_table("column_mappings")
    op.drop_index("ix_staged_records_type_account", table_name="staged_records")
    op.drop_index("ix_staged_records_party", table_name="staged_records")
    op.drop_index("ix_staged_records_document", table_name="staged_records")
    op.drop_table("staged_records")
    op.drop_table("source_rows")
    op.drop_index("ix_reconciliation_lines_status", table_name="reconciliation_lines")
    op.drop_table("reconciliation_lines")
    op.drop_table("quarantined_rows")
    op.drop_table("issue_occurrences")
    op.drop_table("gate_results")
    op.drop_table("dataset_profiles")
    op.drop_index(
        "uq_column_mapping_sets_one_approved",
        table_name="column_mapping_sets",
        postgresql_where=sa.text("status = 'approved'"),
    )
    op.drop_table("column_mapping_sets")
    op.drop_table("rule_runs")
    op.drop_index("ix_rule_exceptions_rule", table_name="rule_exceptions")
    op.drop_table("rule_exceptions")
    op.drop_table("reconciliation_results")
    op.drop_table("readiness_evaluations")
    op.drop_index("ix_issues_status_severity", table_name="issues")
    op.drop_table("issues")
    op.drop_table("imports")
    op.drop_table("entity_candidates")
    op.drop_index(
        "uq_pipeline_runs_succeeded_fingerprint",
        table_name="pipeline_runs",
        postgresql_where=sa.text("status = 'succeeded'"),
    )
    op.drop_index(
        "uq_pipeline_runs_active_fingerprint",
        table_name="pipeline_runs",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_table("pipeline_runs")
    op.drop_table("datasets")
    op.drop_table("approvals")
    op.drop_table("source_systems")
    op.drop_table("policy_versions")
    op.drop_table("change_requests")
    op.drop_table("migrations")
    op.drop_table("stored_files")
    op.drop_table("companies")
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_table("users")
    op.drop_index(
        "ix_jobs_queued", table_name="jobs", postgresql_where=sa.text("status = 'queued'")
    )
    op.drop_table("jobs")
    op.drop_index("ix_audit_events_occurred", table_name="audit_events")
    op.drop_index("ix_audit_events_entity", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
